server:
  port: 8088
  tomcat:
    threads:
      max: 750
      min-spare: 25

spring:
  profiles:
    active: dev
    include: default
  banner:
    location: classpath:/banner.txt
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: happy
    password: happy
    driverClassName: org.h2.Driver
  quartz:
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org:
        quartz:
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
          jobStore:
            class: org.quartz.simpl.RAMJobStore
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

logging:
  level:
    root: INFO

nateon:
  baseurl: https://teamroom.nate.com/api/webhook
  webhookuri: /bf30d923/ZWQvZ4UoqYJN8KEf8ZLnWg6J

batch:
  url: http://localhost:8088/batch/